

services:
  backend:
    build: ./backend
    container_name: day22_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres  

  frontend:
    build: ./frontend
    container_name: day22_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

    postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  


      nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

   volumes:
  pgdata:   
