name: CI Test
on: [push]  # Triggers on push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        run: |
          set -e
          chmod +x system_info.sh
          ./system_info.sh
          echo "Pipeline completed successfully"